name: volunteers_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_core: ^3.8.1
  provider: ^6.1.2
  shared_preferences: ^2.1.0
  flutter_iconly: ^1.0.2
  shimmer: ^2.0.0
  fancy_shimmer_image: ^2.0.2
  dynamic_height_grid_view: ^0.0.3
  card_swiper: ^3.0.1
  image_picker: ^1.1.2
  uuid: ^4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true


  
  assets:
    - assets/images/profile.jpg
    - assets/images/carousel-1.jpg
    - assets/images/carousel-2.jpg
    - assets/images/about-1.jpg
